AllCops:
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'lib/tasks/**/*'
    - 'lib/ab/sample*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
    - 'frontend/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Capfile'
    - 'Gemfile'
  NewCops: enable

# 不要なRDocは書いていない
Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 7

Metrics/AbcSize:
  Enabled: true
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

# 日本語コメント許可
Style/AsciiComments:
  Enabled: false

# 1行のブロックで{...}ではなく、do...endを使用しているかをチェック
# どっちでもよい
Style/MultilineBlockChain:
  Enabled: false

# Rubyの循環的複雑度をチェック
Metrics/CyclomaticComplexity:
  Max: 6

Style/IfInsideElse:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 200

# DSLで書かれている部分以外は、20行縛り
Metrics/BlockLength:
  Max: 20
  Exclude:
    - Gemfile
    - spec/**/*
    - lib/tasks/**/*

# 文字列は"縛り
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Lint/EmptyBlock:
  Enabled: false
